version: '3.1'

services:

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: verdun
