CREATE TABLE user (
id CHAR(24) primary key,
name VARCHAR(256) NOT NULL,
username VARCHAR(64) UNIQUE NOT NULL,
email VARCHAR(128) UNIQUE NOT NULL,
email_verification VARCHAR(16) NOT NULL DEFAULT 'initial',
email_verification_token CHAR(36) NOT NULL,
task_assigned_count INT NOT NULL DEFAULT 0,
password VARCHAR(256) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
