CREATE TABLE task (
id CHAR(24) PRIMARY KEY,
status VARCHAR(64),
title VARCHAR(128) NOT NULL,
description VARCHAR(512),
assigned_to VARCHAR(24),
estimation INT,
created_by VARCHAR(24) NOT NULL,
updated_by VARCHAR(24) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (assigned_to) REFERENCES user(id),
FOREIGN KEY (created_by) REFERENCES user(id),
FOREIGN KEY (updated_by) REFERENCES user(id)
);
