CREATE TABLE priority (
user_id CHAR(24),
task_id CHAR(24),
prev_task_id CHAR(24) NULL,
next_task_id CHAR(24) NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (user_id, task_id),
FOREIGN KEY (task_id) REFERENCES task(id),
FOREIGN KEY (user_id) REFERENCES user(id),
UNIQUE (task_id)
);
